
[server]
host = "example.com"

[database]
server = "127.0.0.1"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true

[logger]
filepath = "movies-ddl.log"
log_level = "debug" # debug, info, warning, error, fatal
